#!/usr/bin/env python3
"""Generate the Module 2 conversion matrix from the planner's data files.

    python scripts/gen_matrix.py           # rewrite docs/CONVERSION_MATRIX.md and docs/conversion-matrix.json
    python scripts/gen_matrix.py --check   # exit 1 if the committed files are stale

The matrix is produced by running the real planner over every
(source, target, mode) combination, so the documentation cannot drift from
what the converter will actually do.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "worker"))

from otk_worker.converter.planner import MODES, Catalog, Route  # noqa: E402

CONVERSION_DIR = ROOT / "resources" / "defaults" / "conversion"
MD_OUT = ROOT / "docs" / "CONVERSION_MATRIX.md"
JSON_OUT = ROOT / "docs" / "conversion-matrix.json"

MODE_MEANING = {
    "PDF / PDF/A / PNG / JPEG / TXT": "Single mode. The page appearance (or plain text) is the only sensible result, so the mode switch is ignored.",
    "DOCX": "**Exact**: page-faithful (positioned frames, page images with hidden OCR text, handouts). **Editable**: flowing paragraphs, real tables and lists.",
    "XLSX": "Both modes give real cells. Exact keeps more styling or adds an 'Original' sheet with the source image.",
    "PPTX": "**Exact**: one slide per page, content at its original position. **Editable**: semantic slides (title + body) or a native per-element rebuild.",
    "HTML": "**Exact**: page-faithful (pages as inline SVG, or the book's own CSS for EPUB). **Editable**: semantic, reflowable HTML.",
    "EPUB": "**Exact**: fixed-layout EPUB 3 (pre-paginated). **Editable**: reflowable EPUB 3.",
    "SVG": "**Exact**: glyph outlines or the embedded original raster, with an invisible text layer. **Editable**: real `<text>` elements and vector shapes.",
}


def short(cat: Catalog, fid: str) -> str:
    return cat.formats[fid].get("short", fid)


def engine_label(cat: Catalog, eid: str) -> str:
    eng = cat.engines[eid]
    return eng["label"] if isinstance(eng, dict) else eid


def route_cell(cat: Catalog, route: Route) -> str:
    chain = " → ".join(short(cat, f) for f in route.chain)
    via = ", ".join(f"[`{s.id}`](#e-{s.id}) ({engine_label(cat, s.engine)})" for s in route.steps)
    extra = f"<br>*Pinned:* {route.override_reason}" if route.override_reason else ""
    return f"{chain}<br><sub>{via}</sub>{extra}"


def loss_cell(cat: Catalog, route: Route) -> str:
    feature_losses = cat.potential_losses(route)
    parts: list[str] = []
    if cat.formats[route.target].get("pixels"):
        if any(cat.features[l.feature]["visual"] for l in feature_losses):
            parts.append("Flattened to pixels (text not selectable)")
        feature_losses = [l for l in feature_losses if not cat.features[l.feature]["visual"]]
    lost = [l.label for l in feature_losses if l.level == "lost"]
    reduced = [l.label for l in feature_losses if l.level == "reduced"]
    if lost:
        parts.append("**Lost:** " + ", ".join(lost))
    if reduced:
        parts.append("**Partial:** " + ", ".join(reduced))
    parts.extend(cat.step_losses(route))
    return " · ".join(parts) if parts else "None expected"


def build(cat: Catalog) -> tuple[str, dict]:
    sources, targets = cat.sources(), cat.targets()
    routes: dict[tuple[str, str], dict[str, Route]] = {}
    for s in sources:
        for t in targets:
            if s == t:
                continue
            per_mode: dict[str, Route] = {}
            for m in MODES:
                if cat.effective_mode(t, m) == m:
                    per_mode[m] = cat.plan(s, t, m)
            routes[(s, t)] = per_mode

    n_pairs = len(routes)
    n_routes = sum(len(v) for v in routes.values())
    lines: list[str] = []
    w = lines.append
    w("# Module 2 conversion matrix")
    w("")
    w("<!-- Generated by scripts/gen_matrix.py from resources/defaults/conversion/*.json. Do not edit by hand. -->")
    w("")
    w(f"**{len(sources)} source formats × {len(targets)} target formats = {n_pairs} conversions, "
      f"{n_routes} planned routes** (targets with two fidelity modes get one route per mode). "
      "Every route below comes from running the real planner (`worker/otk_worker/converter/planner.py`) "
      "on the data files. A test fails if this file is out of date.")
    w("")
    w("## How to read this")
    w("")
    w("- **Route**: the formats a job passes through, then the steps (edge id and engine). Edge ids link to the catalogue at the end.")
    w("- **Potential losses**: what the source format *can* hold that some format on the route cannot, plus losses specific to a step. "
      "*Lost* = cannot be stored in the output. *Partial* = the content survives as plain text or appearance, but its structure does not "
      "(e.g. footnotes become ordinary paragraphs, formulas become their values). "
      "At run time the pre-flight check inspects the actual file and warns only about features it really contains. "
      "The verification report then counts what arrived.")
    w("- `docmodel` and `ocrmodel` are internal JSON models, not files you see. They are shared with Module 3.")
    w("- **Scanned PDF** is not a separate file type. Pages without a text layer are detected when the file is loaded, "
      "and those pages follow the Scanned PDF row. A mixed PDF is split by page and the parts are merged back in order.")
    w("- DOC/XLS/PPT inputs are first normalised to DOCX/XLSX/PPTX by LibreOffice, unless LibreOffice can go straight to the target (PDF, PDF/A).")
    w("")
    w("### What the fidelity modes mean per target")
    w("")
    w("| Target | Meaning |")
    w("|---|---|")
    for k, v in MODE_MEANING.items():
        w(f"| {k} | {v} |")
    w("")
    w("### Steps added to every job (not shown per route)")
    w("")
    w("1. **Pre-flight**: sniff the real type (magic bytes, not the extension), detect encryption, scanned pages, scripts/languages and source features. Warn about expected losses *before* running.")
    w("2. **Password**: encrypted PDF (pikepdf) or Office (msoffcrypto-tool) files prompt for a password. The decrypted copy lives only in the job's temp folder and is deleted afterwards.")
    w("3. **Safe working copies**: inputs are copied to the job folder under ASCII names so every engine handles Unicode paths the same way. Output names are mapped back.")
    w("4. **OCR text layer** (PDF and PDF/A targets from scanned input, on by default): OCRmyPDF adds invisible text and never re-encodes the page images.")
    w("5. **PDF/A validation**: every PDF/A output is checked with veraPDF. On failure the job retries the Ghostscript route, then reports *fail* with the rule list. A PDF/A file that fails is never labelled as PDF/A.")
    w("6. **Verification**: text similarity plus page, image, table, link, footnote, bookmark and font comparisons, reported as HTML and JSON (see [ARCHITECTURE.md §7.4](ARCHITECTURE.md#74-verification-every-job)).")
    w("7. **Packaging**: multi-page outputs to PNG/JPEG/SVG give one file per page, zipped as `name_p001.png`… Optional merge joins several inputs into one output.")
    w("")

    # Summary grid
    w("## Summary grid")
    w("")
    w("Number of steps per route: `exact / editable`, or one number when the target has a single mode. "
      "`ᵒ` = the route runs OCR. `*` = the route is pinned by an override.")
    w("")
    w("| Source \\ Target | " + " | ".join(short(cat, t) for t in targets) + " |")
    w("|---|" + "---|" * len(targets))
    for s in sources:
        cells = []
        for t in targets:
            if s == t:
                cells.append("·")
                continue
            per_mode = routes[(s, t)]
            txt = " / ".join(str(len(r.steps)) for r in per_mode.values())
            if any(any(st.engine == "ocr" for st in r.steps) for r in per_mode.values()):
                txt += "ᵒ"
            if any(r.override_reason for r in per_mode.values()):
                txt += "*"
            cells.append(txt)
        w(f"| **{short(cat, s)}** | " + " | ".join(cells) + " |")
    w("")

    # Per-source detail
    w("## Routes by source format")
    w("")
    for s in sources:
        fmt = cat.formats[s]
        w(f"### {fmt['label']} → …")
        w("")
        if fmt.get("note"):
            w(f"> {fmt['note']}")
            w("")
        w("| Target | Mode | Route | Potential losses |")
        w("|---|---|---|---|")
        for t in targets:
            if s == t:
                continue
            per_mode = routes[(s, t)]
            for m, r in per_mode.items():
                mode_label = m if len(per_mode) > 1 else "—"
                w(f"| {short(cat, t)} | {mode_label} | {route_cell(cat, r)} | {loss_cell(cat, r)} |")
        w("")

    # Edge catalogue
    w("## Edge catalogue")
    w("")
    w("| Edge | Converts | Engine | Modes (cost) | What it does | Step-specific losses |")
    w("|---|---|---|---|---|---|")
    grouped: dict[str, list] = {}
    for e in cat.edges:
        grouped.setdefault(e.id, []).append(e)
    for eid, edges in grouped.items():
        e0 = edges[0]
        pairs = ", ".join(f"{short(cat, e.src)}→{short(cat, e.dst)}" for e in edges)
        modes = ", ".join(f"{m} {c:g}" for m, c in e0.costs.items())
        losses = sorted({l.text for e in edges for l in e.losses})
        final = " (last step only)" if e0.final_only else ""
        w(f"| <a id=\"e-{eid}\"></a>`{eid}` | {pairs}{final} | {engine_label(cat, e0.engine)} | {modes} | {e0.summary} | {'; '.join(losses) or '—'} |")
    w("")

    data = {
        "generatedFrom": ["resources/defaults/conversion/formats.json", "resources/defaults/conversion/routes.json"],
        "pairs": n_pairs,
        "routes": [
            {
                "source": s, "target": t, "mode": m,
                "chain": r.chain,
                "steps": [{"edge": st.id, "engine": st.engine, "from": st.src, "to": st.dst} for st in r.steps],
                "cost": r.cost,
                "override": r.override_reason,
                "potentialLosses": [{"feature": l.feature, "level": l.level} for l in cat.potential_losses(r)],
                "stepLosses": cat.step_losses(r),
            }
            for (s, t), per_mode in routes.items() for m, r in per_mode.items()
        ],
    }
    return "\n".join(lines), data


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if the generated files differ from the committed ones")
    args = ap.parse_args()
    cat = Catalog.from_dir(CONVERSION_DIR)
    md, data = build(cat)
    js = json.dumps(data, indent=1, ensure_ascii=False) + "\n"
    if args.check:
        stale = [p for p, content in ((MD_OUT, md), (JSON_OUT, js))
                 if not p.exists() or p.read_text(encoding="utf-8") != content]
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)} (run scripts/gen_matrix.py)", file=sys.stderr)
        return 1 if stale else 0
    MD_OUT.parent.mkdir(parents=True, exist_ok=True)
    MD_OUT.write_text(md, encoding="utf-8")
    JSON_OUT.write_text(js, encoding="utf-8")
    print(f"wrote {MD_OUT.relative_to(ROOT)} and {JSON_OUT.relative_to(ROOT)}: {data['pairs']} pairs, {len(data['routes'])} routes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
